// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfkft8Rp3N5nA9osFzUe63djnmCtYX0j0',
    appId: '1:510193951239:web:7e26c04e35831c1b30c0a2',
    messagingSenderId: '510193951239',
    projectId: 'easy-map-faf9a',
    authDomain: 'easy-map-faf9a.firebaseapp.com',
    storageBucket: 'easy-map-faf9a.firebasestorage.app',
    measurementId: 'G-K9LPZF0DPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWqsh2doAobFHkqbwE60MR8FMS7MIZZo',
    appId: '1:510193951239:android:052a88853161dee630c0a2',
    messagingSenderId: '510193951239',
    projectId: 'easy-map-faf9a',
    storageBucket: 'easy-map-faf9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuTPIyNPRZpTJGjW7yzydp8ovNHm9ZfM',
    appId: '1:510193951239:ios:3fe821416bfbbe1f30c0a2',
    messagingSenderId: '510193951239',
    projectId: 'easy-map-faf9a',
    storageBucket: 'easy-map-faf9a.firebasestorage.app',
    iosBundleId: 'com.example.easyMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuTPIyNPRZpTJGjW7yzydp8ovNHm9ZfM',
    appId: '1:510193951239:ios:3fe821416bfbbe1f30c0a2',
    messagingSenderId: '510193951239',
    projectId: 'easy-map-faf9a',
    storageBucket: 'easy-map-faf9a.firebasestorage.app',
    iosBundleId: 'com.example.easyMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfkft8Rp3N5nA9osFzUe63djnmCtYX0j0',
    appId: '1:510193951239:web:893c1958a01178da30c0a2',
    messagingSenderId: '510193951239',
    projectId: 'easy-map-faf9a',
    authDomain: 'easy-map-faf9a.firebaseapp.com',
    storageBucket: 'easy-map-faf9a.firebasestorage.app',
    measurementId: 'G-FFLHKSKSWF',
  );
}
